HxHexa/frieren-tcg

src/commands/tcgInfo/info/gameAdvancedRules.ts

PR Seems bit of an overkill but whatever

fix: typo in /tcg info how-to-play

---

src/commands/tcgChallenge/gameHandler/initiateChallengeRequest.ts
src/commands/tcgChallenge/gameHandler/utils/buildChallengeButtonRespond.ts
src/commands/tcgChallenge/gameHandler/utils/handleOpponent.ts
src/commands/tcgChallenge/tcgChallenge.ts
src/commands/tcgChallenge/tcgChallengeCustom.ts

add open invites

---

src/tcg/card.ts

Hi Hexa ur da best also you could probably have done this in 5s yourself but hey it's good practice.

empowered effects now display in bold

---

src/tcg/card.ts

better code formatting

---

src/commands/tcgAdmin/achievementHandler/handleManageAchievement.ts
src/commands/tcgAdmin/tcgAdmin.ts
src/commands/tcgChallenge/gameHandler/utils/buildChallengeButtonRespond.ts

Resolves #50 
Create an achievement
Delete achievement

feat: Add achievement management commands

---

.vscode/extensions.json
eslint.config.mjs
package-lock.json
package.json
src/commands/tcgAdmin/tcgAdmin.ts
src/commands/tcgInfo/info/gameHowToPlay.ts
src/commands/tcgRanked/rankedHandlers/characterStats.ts
src/commands/tcgRanked/rankedHandlers/globalStats.ts
src/commands/tcgRanked/rankedHandlers/leaderboardEmbed.ts
src/commands/tcgRanked/tcgRanked.ts
src/tcg/character.ts
src/tcg/decks/LinieDeck.ts
src/tcg/decks/SeinDeck.ts
src/tcg/decks/SerieDeck.ts
src/tcg/decks/StarkDeck.ts
src/tcg/decks/StilleDeck.ts
src/tcg/decks/monsterDecks/AngryMimicDeck.ts
src/tcgChatInteractions/printCharacter.ts
src/tcgChatInteractions/sendGameMessage.ts
src/tcgMain.ts
src/util/createCharacterDropdown.ts
src/util/messageComponents/characterSelect.ts
src/util/utils.ts

Will be used in other files later but its a function now

extract character dropdown

---

eslint.config.mjs
src/commands/tcgRanked/rankedHandlers/characterStats.ts
src/commands/tcgRanked/tcgRanked.ts
src/util/messageComponents/characterSelect.ts
src/util/utils.ts

Character Selector and Overview for Character Stats

---

src/commands/tcgChallenge/gameHandler/initiateGame.ts
src/tcgMain.ts

fix undefined character embed section when tied

---

src/tcg/card.ts
src/tcg/gameContextProvider.ts
src/tcg/timedEffect.ts

1. Get the new system setup, make any adjustments, organization or general changes
See #93

Card Actions context provider

---

src/tcg/decks/FrierenDeck.ts
src/tcg/decks/SenseDeck.ts
src/tcg/decks/StarkDeck.ts
src/tcg/gameContextProvider.ts

Card Actions Refactor: Sense & Frieren

---

package-lock.json
package.json
src/commands/tcgMeta/metaHandlers/showEmojiList.ts
src/commands/tcgMeta/tcgMeta.ts

update discord js and add tcg-meta with list emoji subcommand

---

src/main.ts

Make sure bot never crashes, this doesnt solve the issue of Unhandled Interactions but this is a standard to have in most discord bots

feat: anticrash

---

src/tcg/characters/characterData/characters/Frieren.ts
src/tcg/decks/DenkenDeck.ts
src/tcg/decks/FernDeck.ts
src/tcg/decks/FrierenDeck.ts
src/tcg/decks/HimmelDeck.ts
src/tcg/decks/LaufenDeck.ts
src/tcg/decks/LinieDeck.ts
src/tcg/decks/SeinDeck.ts
src/tcg/decks/SenseDeck.ts
src/tcg/decks/SerieDeck.ts
src/tcg/decks/StarkDeck.ts
src/tcg/decks/StilleDeck.ts
src/tcg/decks/UbelDeck.ts
src/tcg/decks/monsterDecks/FireGolemDeck.ts
src/tcg/decks/monsterDecks/ShadowDragonDeck.ts
src/tcg/decks/monsterDecks/StoneGeiselDeck.ts
src/tcg/decks/monsterDecks/StoneGolemDeck.ts
src/tcg/timedEffect.ts
src/util/createCharacterDropdown.ts

Realized removeableBySorganeil is supposed to be true by default, fixing now

Metadata (and defaults) for TimedEffects + Sort favorite preferences alphabetically too

---

docker-compose.yml
src/commands/tcgStats/statsHandlers/characterStats.ts
src/commands/tcgStats/statsHandlers/handleUsageStats.ts
src/commands/tcgStats/tcgStats.ts

tcg-stats usage

---

package-lock.json
package.json
src/commands/tcgPlayer/playerHandlers/profileEmbed.ts
src/commands/tcgStats/statsHandlers/characterLeaderboard.ts
src/commands/tcgStats/statsHandlers/exportTable.ts
src/commands/tcgStats/statsHandlers/globalStats.ts
src/commands/tcgStats/statsHandlers/leaderboardEmbed.ts
src/commands/tcgStats/tcgStats.ts
src/setupInteractions.ts
src/util/db/getTables.ts

Winrate in ranked and character leaderboard + stats export

---

package-lock.json
package.json

https://github.com/HxHexa/frieren-tcg/security/dependabot/1

3.1 vulnerability from dependabot

---

src/tcg/card.ts
src/tcg/decks/DenkenDeck.ts
src/tcg/decks/FernDeck.ts
src/tcg/decks/FrierenDeck.ts
src/tcg/decks/HimmelDeck.ts
src/tcg/decks/LaufenDeck.ts
src/tcg/decks/LinieDeck.ts
src/tcg/decks/SeinDeck.ts
src/tcg/decks/SenseDeck.ts
src/tcg/decks/SerieDeck.ts
src/tcg/decks/StarkDeck.ts
src/tcg/decks/StilleDeck.ts
src/tcg/decks/UbelDeck.ts
src/tcg/decks/monsterDecks/AngryMimicDeck.ts
src/tcg/decks/monsterDecks/CosmicTonDeck.ts
src/tcg/decks/monsterDecks/FireGolemDeck.ts
src/tcg/decks/monsterDecks/ShadowDragonDeck.ts
src/tcg/decks/monsterDecks/StoneGeiselDeck.ts
src/tcg/decks/monsterDecks/StoneGolemDeck.ts
src/tcg/decks/utilDecks/defaultCard.ts
src/tcg/decks/utilDecks/serieSignature.ts
src/tcg/decks/utilDecks/ubelSignature.ts

Please make sure i didnt break anything.

Added dynamic hpCost and priority to cards

---

src/commands/tcgChallenge/gameHandler/utils/buildChallengeButtonRespond.ts

add trycatch and stop collector when failing to edit message

---

src/commands/tcgPreferences/preferencesHandlers/preferencesHandler.ts
src/tcg/characters/characterData/characters/Edel.ts

glorp
- Use "she" instead of "her" in 
- Set minimum values to `0` because the default is `1` in favorite character selector

General fixes

---

src/commands/tcgAdmin/tcgAdmin.ts
src/commands/tcgChallenge/gameHandler/handleDatabaseOperations.ts
src/commands/tcgChallenge/gameHandler/initiateGame.ts
src/commands/tcgChallenge/gameHandler/utils/buildChallengeButtonRespond.ts
src/commands/tcgChallenge/gameHandler/utils/handleOpponent.ts
src/commands/tcgChallenge/gameHandler/utils/sendMoveThreadMessage.ts
src/commands/tcgChallenge/gameHandler/utils/validateMatchButtonInteractions.ts
src/commands/tcgPreferences/preferencesHandlers/preferencesHandler.ts
src/commands/tcgStats/statsHandlers/characterStats.ts
src/setupInteractions.ts
src/tcg/decks/FlammeDeck.ts
src/tcgMain.ts
src/ui/battleResults.ts
src/ui/challengeRequest.ts
src/util/createCharacterDropdown.ts
src/util/formatting/links.ts
src/util/messageComponents/characterSelect.ts

UI Redesign

---

prisma/migrations/20250503131501_add_player_preferences/migration.sql
prisma/schema.prisma
src/commands/tcgChallenge/gameHandler/initiateChallengeRequest.ts
src/commands/tcgChallenge/gameHandler/utils/buildChallengeButtonRespond.ts
src/commands/tcgChallenge/tcgChallenge.ts
src/commands/tcgChallenge/tcgChallengeCustom.ts
src/commands/tcgChallenge/tcgChallengeRanked.ts
src/commands/tcgPreferences/preferencesHandlers/preferencesHandler.ts
src/commands/tcgPreferences/tcgPreferences.ts
src/constants.ts
src/tcg/decks/FernDeck.ts
src/tcg/decks/HimmelDeck.ts
src/tcg/decks/LaufenDeck.ts
src/tcg/decks/SeinDeck.ts
src/tcg/decks/SerieDeck.ts
src/tcg/decks/StarkDeck.ts
src/tcg/decks/StilleDeck.ts
src/tcg/decks/UbelDeck.ts
src/tcg/decks/utilDecks/serieSignature.ts
src/tcg/decks/utilDecks/ubelSignature.ts
src/tcg/formatting/mediaLinks.ts
src/util/db/preferences.ts

Using the set-invite-length command
Can be changed for one invite within the challenge commands, but doesn't change the preference.

Issue #152, slightly altered from orignal goal to instead make invite length customisable from 1 to 15 minutes

---

prisma/migrations/20250919180000_add_ban_config/migration.sql
prisma/migrations/20260218120000_add_character_bans/migration.sql
prisma/schema.prisma
prisma/seed.ts
src/commands/tcgAdmin/tcgAdmin.ts
src/commands/tcgChallenge/gameHandler/gameSettings.ts
src/commands/tcgChallenge/gameHandler/handleDatabaseOperations.ts
src/commands/tcgChallenge/gameHandler/initiateChallengeRequest.ts
src/commands/tcgChallenge/gameHandler/initiateGame.ts
src/commands/tcgChallenge/gameHandler/utils/buildChallengeButtonRespond.ts
src/commands/tcgChallenge/tcgChallenge.ts
src/commands/tcgChallenge/tcgChallengeCustom.ts
src/commands/tcgChallenge/tcgChallengeRanked.ts
src/commands/tcgStats/statsHandlers/banRates.ts
src/commands/tcgStats/tcgStats.ts
src/tcgChatInteractions/getPlayerBans.ts
src/tcgChatInteractions/getPlayerCharacter.ts
src/tcgChatInteractions/handleCharacterSelection.ts
src/tcgMain.ts
src/ui/challengeRequest.ts
src/util/createCharacterDropdown.ts
src/util/db/banConfig.ts
src/util/db/createMatch.ts

no more hard counters or annoying characters (looking at you Sein/Aura players)

feat: Implement Ban System
